# 项目相关配置
need:
  # 名称
  name: Need
  # 版本
  version: 3.8.3
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: F:/need/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

server:
  port: 3000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xiaomi?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true